name: Generate Video with VOICEVOX

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to scrape for dialogue content'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      voicevox:
        image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
        ports:
          - 50021:50021

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Japanese fonts
      run: sudo apt-get install -y fonts-noto-cjk

    - name: Install ffmpeg
      run: sudo apt-get install -y ffmpeg

    - name: Add user dict
      run: python3 user_dict/user_dict_manager.py

    - name: Run main script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        if [ -n "${{ github.event.inputs.url }}" ]; then
          python3 main.py "${{ github.event.inputs.url }}"
        else
          python3 main.py
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: final-video
        path: final_dialogue_output.mp4
