name: Generate Video with VOICEVOX

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      voicevox:
        image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
        ports:
          - 50021:50021

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Japanese fonts
      run: sudo apt-get install -y fonts-noto-cjk

    - name: Install ffmpeg
      run: sudo apt-get install -y ffmpeg

    - name: Run main script
      run: python3 main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: final-video
        path: final_dialogue_output.mp4
